### ISSUE TITLE
getBucket() and file timestamp 

### ISSUE THREAD

**Issue by sergio-paternoster** [akeeba/s3#19]
I'm using the getBucket() method to list the content of a folder in a bucket. Once I get the list of files, I need to check the last modified datetime. The array returned by getBucket() has a "time" element but this doesn't look like the last modified date of the file but more the time when the object has been created in the folder.
I try to explain myself a bit better. 

If you have a file in a bucket/folder created on 2021-01-29 10:00:00 and you copy it into another folder in S3 on 2021-11-22 07:30:00 then getBucket() returns the timestamp of 2021-11-22 07:30:00 (create date of the file in the new folder) and not the original 2021-01-29 10:00:00 (original create date) 

I see the "time" comes from 
```
'time' => strtotime((string) $c->LastModified)
```

Is there any possibility to get the real file create datetime and not the modified one?

**Comment by capsandiego** [comment]
Yes, it would be great if we could get the file "create date" instead of the "last modified" one. 
Is it possible?

**Comment by ryandemmer** [comment]
No, the AWS S3 object metadata only provides _LastModified_- https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingMetadata.html

**Comment by nikosdion** [comment]
No, the Amazon S3 API does not return this information. Reference: https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjects.html and https://docs.aws.amazon.com/AmazonS3/latest/API/API_Object.html

**Comment by nikosdion** [comment]
@ryandemmer You beat me to the punch 😄

**Comment by ryandemmer** [comment]
I have to contribute to this excellent library somehow! 😜
