### ISSUE TITLE
getAuthenticatedURL does not honor setUseLegacyPathStyle

### ISSUE THREAD

**Issue by jeffmikels** [akeeba/s3#29]
When using Legacy path style, the getAuthenticatedURL method returns urls like this:

`https://[ENDPOINT]/[FILEPATH]`

but it should be returning:

`https://[ENDPOINT]/[BUCKET]/[FILEPATH]`

**Comment by nikosdion** [comment]
Pre-signed URLs can not be created for legacy path style bucket access. See https://docs.aws.amazon.com/IAM/latest/UserGuide/create-signed-request.html
