### ISSUE TITLE
getObject cannot get XML files

### ISSUE THREAD

**Issue by jeffmikels** [akeeba/s3#30]
If I attempt to get an XML file from a bucket, the Response class will think the XML is an error message from amazon and will parse the body into a SimpleXMLElement and then somehow reset the actual body content to the last received chunk, failing to return the correct xml content.

Saving to a file still works because that happened during the response, but returning as a string fails to return the expected content.

**Comment by jeffmikels** [comment]
I solved it for me by editing the `finaliseBody` function. I save the body to a raw_body field before parsing it, and then I changed getObject to return the raw_body value to the caller instead of the body value.

**Comment by nikosdion** [comment]
Good catch. I updated the logic throughout the chain of calls all the way to the Request object to allow getObject to return the data verbatim, without trying to parse it.
