### ISSUE TITLE
Support for DreamObject s3

### ISSUE THREAD

**Issue by bcordis** [akeeba/s3#36]
Your code does not look like the security key generated.

The URL must not include HTTP. This looks to be developed in S3Filesystem.php getFormConnection

The code on Request.php does not need to add the bucket to the URL, like line 672.

Also, I have been trying to get the thumbnails to work right, as it keeps letting them oversize.

Let me know what you would like me to test the necessary info.

**Comment by nikosdion** [comment]
> Your code does not look like the security key generated.

I have no idea what you mean with this. What security key? S3 does not have any such concept. It has an Access Key and a Secret Key and you need to provide both of them yourself.

> The URL must not include HTTP. This looks to be developed in S3Filesystem.php getFormConnection

There is no such file in this repository. What are you talking about...?

> The code on Request.php does not need to add the bucket to the URL, like line 672.

What are you even talking about? This is part of the code which **PARSES** the HTTP headers. It reads the headers sent by the server.

> Also, I have been trying to get the thumbnails to work right, as it keeps letting them oversize.

This is a library which uploads and downloads files to/from S3 and S3-compatible services. What thumbnails are you even talking about? There is no such functionality.

> Let me know what you would like me to test the necessary info.

Are you sure you are submitting an issue to the correct repository? I will go with no.
