### ISSUE TITLE
Viewing a folder from S3

### ISSUE THREAD

**Issue by SolutionsDEV** [akeeba/s3#5]
Good day,

What I am trying to do is to upload a folder in S3, this folder will be protected so cannot be accessed directly, then I want to use a script that is hosted somewhere else to read the index file of that folder and view it on the website that is hosted at the other location as if it is on that server and of course the index file will be linked to many other files in that folder which should all work as a view from the hosted pages externally.

This process will be repeated to many other folders, which will create the need for an interface to manage S3 views on that website, but they all would have the same API details.

Uploading files through the script is not much of important to me.

Can this script work like this? Which part of it?

Would you kindly help me?

Sorry that I had to post here, but did not find any contact, help or description.

Thanks a lot in advance,

**Comment by MikeVelazcoMtz** [comment]
Actually, I think that you grant access to folders/buckets via AWS access list or groups filtering by the server IP address. This way you only need to worry about the logic required to bring the files

**Comment by nikosdion** [comment]
This repository contains a PHP programming library which allows you to upload, download and list files on Amazon S3 buckets. It is not an end user client script. If you have no idea what that means then you are probably looking at the wrong repository for what you are trying to do. 

If you want to develop your own solution you should look at [the Connector class](https://github.com/akeeba/s3/blob/master/src/Connector.php). You initialize it by first creating a `Configuration` object. The parameters (properties) of the Configuration class are self-explanatory and documented in the code. Likewise, the methods of the Connector class are documented and mostly allude to the Amazon S3 REST API method names. So I guess you shouldn't have a problem figuring out how to use this small library :)
